### ISSUE TITLE
In Mac OS X CMD-j does not work, though Ctrl-j works

### ISSUE THREAD

**Issue by eugene-sea** [wmaurer/vscode-join-lines#2]
On my MacBook Pro on pressing ⌘-j nothing happens. Ctrl-j works OK. Ideally ⌘-j should work also

**Comment by eugene-sea** [comment]
By the way I have been waiting for join lines hot-key in VSCode for a long time. Thank you.

**Comment by capyvara** [comment]
Maybe changing the keybind to cmd+j already maps to ⌘ on OSX and Control on Windows?

**Comment by eugene-sea** [comment]
If I add the following binding to my keybindings.json, it works:

``` JSON
{
  "key": "cmd+j",
  "command": "extension.join-lines"
}
```

**Comment by wmaurer** [comment]
Ok, so this the first time anyone's raised an issue on one of my repos, so I didn't know I need to watch it in order to get notified ...

@eugene-sea I'm glad you like the extension.

I had no idea that the keybindings would be different on a Mac. @Capyvara, I tried Cmd+j, and it doesn't map to Ctrl on Windows.

Maybe I should map both so that it works for Windows and Mac users as soon as the extension is installed. I'll make a change and release a new version.

**Comment by wmaurer** [comment]
I've added the Cmd+j keybinding in commit bcf05ca4c29943f8af32970111dedf1a0665232e, so you should be able to remove it from your personal keybindings.

**Comment by eugene-sea** [comment]
Thank you
